name: CI/CD

on:
  push:
    branches: [ QuizApp_v2 ]
  pull_request:
    branches: [ QuizApp_v2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: 'rahhul17sj/quiz-app:latest'

